[custom.all.idris2-textdao]
type = "local"
path = "/Users/bob/code/idris2-textdao"
ipkg = "idris2-textdao.ipkg"

[custom.all.textdao-tests]
type = "local"
path = "/Users/bob/code/idris2-textdao"
ipkg = "tests.ipkg"

[custom.all.idris2-subcontract]
type = "local"
path = "/Users/bob/code/idris2-subcontract"
ipkg = "idris2-subcontract.ipkg"

[custom.all.idris2-yul]
type = "local"
path = "/Users/bob/code/idris2-yul"
ipkg = "idris2-yul.ipkg"
